packages:
  - .
  - playground
catalog:
  '@ntnyq/eslint-config': ^4.0.3
  '@ntnyq/prettier-config': ^2.0.0
  '@nuxt/eslint-config': ^1.3.0
  '@nuxt/kit': ^3.16.2
  '@nuxt/module-builder': ^1.0.1
  '@nuxt/schema': ^3.16.2
  '@types/node': ^22.14.0
  '@unocss/nuxt': ^66.1.0-beta.10
  '@unocss/reset': ^66.1.0-beta.10
  bumpp: ^10.1.0
  defu: ^6.1.4
  eslint: ^9.24.0
  husky: ^9.1.7
  nano-staged: ^0.8.0
  npm-run-all2: ^7.0.2
  nuxt: ^3.16.2
  premove: ^4.0.0
  prettier: ^3.5.3
  tsx: ^4.19.3
  typescript: ^5.8.3
  unocss: ^66.1.0-beta.10
  viewerjs: ^1.11.7
  vitest: ^3.1.1
overrides:
  esbuild: ^0.25.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
