packages:
  - .
  - playground
catalog:
  '@ntnyq/eslint-config': ^4.3.0
  '@ntnyq/prettier-config': ^2.2.0
  '@nuxt/eslint-config': ^1.4.1
  '@nuxt/kit': ^3.17.5
  '@nuxt/module-builder': ^1.0.1
  '@nuxt/schema': ^3.17.5
  '@types/node': ^22.15.34
  '@unocss/nuxt': ^66.3.2
  '@unocss/reset': ^66.3.2
  bumpp: ^10.2.0
  defu: ^6.1.4
  eslint: ^9.30.0
  husky: ^9.1.7
  nano-staged: ^0.8.0
  npm-run-all2: ^8.0.4
  nuxt: ^3.17.5
  premove: ^4.0.0
  prettier: ^3.6.2
  tsx: ^4.20.3
  typescript: ^5.8.3
  unocss: ^66.3.2
  viewerjs: ^1.11.7
  vitest: ^3.2.4
overrides:
  esbuild: ^0.25.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
