catalog:
  '@nuxt/kit': ^3.15.4
  '@nuxt/schema': ^3.15.4
  '@unocss/nuxt': ^65.4.3
  '@unocss/reset': ^65.4.3
  '@vitest/coverage-v8': ^3.0.5
  nuxt: ^3.15.4
  unocss: ^65.4.3
  viewerjs: ^1.11.7
  vitest: ^3.0.5
packages:
  - .
  - playground
